name: Enforce PR title includes Jira Issue Key

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run PR title check
        uses: ./
